sudo: false

language: php

php:
  - 5.6
  - 7
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - sudo pip install codecov

script:
    - phpunit --coverage-text

after_script:
  - php vendor/bin/codacycoverage clover build/logs/clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - codecov
